### ISSUE TITLE
v3.0.0 Checklist

### ISSUE THREAD

**Issue by envygeeks** [jekyll/jekyll-assets#417]
- [x] Boot sprockets only once if possible.
- [x] Convert our configuration to Symbols.
- [x] Move to HashWithIndifferentAccess for Config.
- [x] Move all plugins into a plugins folder, they shouldn't be called addons.
- [x] Change the way proxies work so we can get more efficient and work within Sprockets a lot better.
- [x] Complete every milestone https://github.com/jekyll/jekyll-assets/milestone/12
- [x] Move the parser to ***envygeeks/liquid-tag-parser***
- [x] Reduce the complexity we have with Liquid.
- [x] Rework how Proxies are made.
- [x] Fix caching.

### Rewrites

- [x] image_optim plugin doesn't meet my coding standards.
- [x] magick plugin doesn't meet my coding standards.
